### ISSUE TITLE
A tiny bug in data processing

### ISSUE THREAD

**Issue by hwlza** [ThyrixYang/es_dfm#5]
hi, Thanks for your work and contributing it to the community. :) I found a typo bug when preparing the criteo dataset as follows: https://github.com/ThyrixYang/es_dfm/blob/9183c119746a4825e5c062324d7d39aea8cfa6c5/src/data.py#L428

I think the ` "sample_ts": train_data.sample_ts` should be  ` "sample_ts": test_data.sample_ts` although this bug would not take effect on the pre-training results, only when one wants to make some evaluations in the pre-training stage.

**Comment by ThyrixYang** [comment]
Hi @hwlza ,

We appreciate your interest in our work, and we are grateful for your observation regarding this minor typo. We have rectified this typo based on your suggestion. 
We hope our code can be useful for your work. :)

**Comment by ThyrixYang** [comment]
Hi, @hwlza 

Fixed. Thank you! I think this bug is introduced in the open-source version.

**Comment by hwlza** [comment]
Have a nice day. Thanks for your excellent work. :smile:
