### ISSUE TITLE
想问下能否不添加任务的情况下利用延迟Label做无偏估计？

### ISSUE THREAD

**Issue by shichengcn** [ThyrixYang/es_dfm#8]
大佬您好，我这边尝试了FNW，因为这个loss要求初始时刻全部样本当做负样本先下发一次，我这边却只下发延迟正样本，直接使用有一定效果，但是打分均值会高出50%，感觉不够合理。

参考您的方案，需要添加辅助模型，想咨询下，是否可以达到这样
（1）延迟下发的逻辑是先固定一个初始窗口，观察即时转化行为，后续补充只下发延迟正样本
（2）loss函数 使用  三个变量   label，predict，is_delay_label
其中 label为标签，predict为模型预测值，is_delay_label 为是否是延迟下发的正样本标记

这样相比您的论文中，没用使用到 tn和dp的预估来辅助。

这样是否能够做到无偏估计呢？

**Comment by ThyrixYang** [comment]
@shichengcn 不管你怎么做样本的下发都是对样本流的分布做了改变，如果需要无偏的估计肯定是需要对应的对loss做纠偏的。我们是用辅助模型来估计纠偏的权重，可能也可以采用其他方式，但是肯定是要做相应的纠偏处理的

**Comment by shichengcn** [comment]
大佬您好，我这边有一个这种思路，您看是不是可行
<img width="401" alt="image" src="https://github.com/ThyrixYang/es_dfm/assets/26249035/80df9f18-0616-4789-ab4f-d7cf5dd47983">

**Comment by ThyrixYang** [comment]
@shichengcn 你这个就相当于在所有的输出上做一个修正，其实你可以直接在输出上乘一个系数，均值就可以纠正。但是这和无偏是两个概念，无偏是指p(y|x)和真实值接近，而不是均值接近

**Comment by ThyrixYang** [comment]
@shichengcn 我建议是你先试试你这个方法是否可以达到你的需要，如果简单的纠正均值就够用那是没问题的

**Comment by shichengcn** [comment]
非常感谢您的答复。
我比较疑惑的地方就是我现在采用了只下发延迟正样本的方式，在这种方式下都是需要辅助模型的。
不需要辅助模型的，例如FNW是t0时刻全部当做负样本先下发一次，Defer是所有样本都会以正确Label重新下发一次，和我的处理方式不同。

在不想引入辅助模型的情况下，采用只下发延迟正样本的方式，可以只调整loss来达到无偏估计吗?或者您了解有类似的论文么
目前使用FNW的loss，有效果，但是感觉逻辑上不是很自洽，因为我只下发了延迟正样本。

**Comment by ThyrixYang** [comment]
@shichengcn 现在的论文和FNW或者ESDFM的思路都差不多，我们推导出来的结果就是必须有一个辅助的模型才能无偏。实际上你也不一定要用fnw的loss，你直接用cross entropy得到的AUC应该也差不多的，如果你只需要均值对齐的话完全可以按你的做法做

**Comment by shichengcn** [comment]
”直接用cross entropy“是指的，样本上进行延迟正样本下发，模型上完全不改动，直接交叉熵训练么？
我这边实验直接全部训练有些负向，调整权重后可以有些收益。
万分感谢大佬的答复~
那我也上一下辅助模型吧
